trigger:
- master

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
    - repository: templates
      type: git
      ref: refs/tags/old
      name: pipeline-templates

extends:
  template: Build\dotnet.yml@templates
