trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '**/*.csproj'
    exclude:
    - '**/*Tests.csproj'

pool:
  vmImage: 'windows-latest'

variables:
- group: date-override

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      publishTestResults: false
      projects: |
        **\*Tests.dll
        !**\obj\**
      testRunTitle: 'Test'

  - task: DotNetCoreCLI@2
    displayName: 'Pack'
    inputs:
      command: 'pack'
      packagesToPack: '**\*.csproj;!**\*Tests.csproj'
      nobuild: true
      versioningScheme: 'off'

  - task: PowerShell@2
    displayName: 'Publish package'
    inputs:
      workingDirectory: $(Build.ArtifactStagingDirectory)
      targetType: 'inline'
      script: |
        dir
        dotnet nuget push *.nupkg -k $(NUGET_API_KEY) -s https://api.nuget.org/v3/index.json --skip-duplicate
