trigger:
  branches:
    include:
    - master
  paths:
    include:
    - '**/*.csproj'
    exclude:
    - '**/*Tests.csproj'

pool:
  vmImage: 'windows-latest'

steps:
  - task: PowerShell@2
    displayName: 'Get solution path'
    inputs:
      targetType: 'inline'
      script: |
        $solutionPath = Get-ChildItem -Filter *.sln -Recurse | Select-Object -Expand Directory -First 1

        Write-Host "##vso[task.setvariable variable=solutionPath]$solutionPath"

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      workingDirectory: "$(solutionPath)"

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      publishTestResults: false
      projects: |
        **\*Tests.dll
        !**\obj\**
      testRunTitle: 'Test'

  - task: DotNetCoreCLI@2
    displayName: 'Pack'
    inputs:
      command: 'pack'
      packagesToPack: '**\*.csproj;!**\*Tests.csproj'
      nobuild: true
      versioningScheme: 'off'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'custom'
      projects: '**/*.nupkg'
      custom: 'nuget push'
      arguments: '-k $(NUGET_API_KEY) -s https://api.nuget.org/v3/index.json --skip-duplicate'