name: .NET Core - Build & Test

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '**/README.md'
    - '**/*.yml'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest 
    defaults:
      run:
        working-directory: DateOverride     

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
      
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
            
    - name: Test
      run: dotnet test --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../lcov /p:CopyLocalLockFileAssemblies=true
    
#     - name: Install OpenCover
#       run: choco install opencover.portable

#     - name: Generate cover report
#       run: OpenCover.Console.exe -target:"dotnet.exe" -targetargs:test -register:Path64 -oldstyle

#     - name: Publish cover report
#       uses: codecov/codecov-action@v1.0.11

    - name: Codecov
      uses: codecov/codecov-action@v1.0.12
      with:
        directory: *

  
